### ISSUE TITLE
Failed actually to parse the OGC URN pattern

### ISSUE THREAD

**Issue by usagi** [sgodwincs/uriparse-rs#10]
## Repro

Parse a OGC URN pattern:

```rust
use std::convert::TryFrom;
let urn = "urn:ogc:def:crs,crs:EPSG::31256"; // See also https://www.ogc.org/ogcUrnPolicy
let x: uriparse::URIReference = uriparse::URIReference::try_from(urn).unwrap(); // Ok
println!("{:?}", x);
```

Then, I got:

```
URIReference { authority: None, fragment: None, path: Path { absolute: false, double_dot_segment_count: 0, leading_double_dot_segment_count: 0, segments: [Segment { normalized: true, segment: "ogc:def:crs,crs:EPSG::31256" }], single_dot_segment_count: 0, unnormalized_count: 0 }, query: None, scheme: Some(URN) }
```

It's `Ok` of `Result`, but it not an expected result. `authority` and many parts are actually empty. And almost parts be pushed into the `segment`.

**Comment by sgodwincs** [comment]
The result here is expected. This crate is for parsing URIs specifically, not URNs. While URNs are URIs, they may have some structure internal to their scheme as described in your link. You can see here in [RFC3986](https://tools.ietf.org/html/rfc3986#section-3) though that they give an example of a URN URI, where everything after `urn:` is part of the path.
