### ISSUE TITLE
Release for stable

### ISSUE THREAD

**Issue by chrysn** [sgodwincs/uriparse-rs#11]
With the non_exhaustive feature removed, uriparse-rs now builds on stable unlike the latest published version. It would be convenient to have a recent version uploaded to crates.io in order for crates building on stable to use it.

**Comment by chipsenkbeil** [comment]
This and #9 are what are keeping me from using this to parse URIs for a vimwiki server. Is there any headway here?

I was getting by with the url crate, but I hit one of the spec differences and need this one instead.

**Comment by sgodwincs** [comment]
Published version 0.6.2.
