### ISSUE TITLE
support for stable channel

### ISSUE THREAD

**Issue by davidB** [sgodwincs/uriparse-rs#5]
Hi,

Do you plan to release a version on rust' stable in a near future ?

**Comment by sgodwincs** [comment]
Currently, the last nightly feature remaining is non-exhaustive enums. From what I understand, this is expected to be stabilized relatively shortly, hopefully in a couple of releases or so.

**Comment by ArturKovacs** [comment]
I'm interested as well. I would love to use this crate but unfortunately I can't until it doesn't support the stable channel.

**Comment by sgodwincs** [comment]
Looks like non_exhaustive was just stabilized. Since it was stabilized before the 1.39 release, I think it should be out in the 1.40 release, 1.41 at the latest.

There's actually some improvements I want to make, so this will give me some time.
