### ISSUE TITLE
Decode UTF-8 string from path

### ISSUE THREAD

**Issue by ArturKovacs** [sgodwincs/uriparse-rs#7]
Hi!

If I have a URI path where certain UTF-8 byte sequences were encoded, can I retrieve the original UTF-8 `String` using this crate? I tried the following which simply prints
`/path/to/I%E2%9D%A4%EF%B8%8FURIs`.
```rust
let uri = "/path/to/I%E2%9D%A4%EF%B8%8FURIs";
// uriparse Path
let path = Path::try_from(uri).unwrap();
assert!(path.is_normalized(true));
println!("{}", path);
```

**Comment by sgodwincs** [comment]
There's no way to do this with this crate. What you are looking for is an IRI (https://tools.ietf.org/html/rfc3987).

Alternatively, have you tried using the url crate? They are not exactly the same, but unless you specifically need a URI or IRI, I'd go with that.

**Comment by ArturKovacs** [comment]
Ah thank you for the info. I managed to achieve what I wanted with the url crate.
