### ISSUE TITLE
Serde feature

### ISSUE THREAD

**Issue by theduke** [sgodwincs/uriparse-rs#9]
Would be very nice to have a optional `serde` feature that implements `Serialize` and `Deserialize` for `URI`.

**Comment by sgodwincs** [comment]
I still have some pending changes I need to finish, but I'll put this on my todo list.

**Comment by sgodwincs** [comment]
I haven't used serde much, is it expected that the serialization would just be the URI as a string? Or maybe serialized as a struct of its components?

**Comment by theduke** [comment]
A string makes the most sense.
